# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\User\project.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import img.image

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1240, 785)
        self.stack = QtWidgets.QWidget(MainWindow)
        self.stack.setEnabled(True)
        self.stack.setObjectName("stack")
        self.entry = QtWidgets.QStackedWidget(self.stack)
        self.entry.setGeometry(QtCore.QRect(0, 0, 1261, 771))
        self.entry.setObjectName("entry")
        self.opening = QtWidgets.QWidget()
        self.opening.setObjectName("opening")
        self.open_bg = QtWidgets.QLabel(self.opening)
        self.open_bg.setGeometry(QtCore.QRect(0, -70, 1351, 871))
        self.open_bg.setOpenExternalLinks(False)
        self.open_bg.setObjectName("open_bg")
        self.open_button = QtWidgets.QPushButton(self.opening)
        self.open_button.setGeometry(QtCore.QRect(350, 530, 451, 101))
        self.open_button.setStyleSheet("QPushButton{\n"
"    font: 40pt \"Guttman Yad-Brush\";\n"
"    color: rgb(0, 85, 255);\n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 170, 255);\n"
"}")
        self.open_button.setObjectName("open_button")
        self.entry.addWidget(self.opening)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.loguser_input = QtWidgets.QLineEdit(self.login_page)
        self.loguser_input.setGeometry(QtCore.QRect(450, 320, 351, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.loguser_input.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.loguser_input.setFont(font)
        self.loguser_input.setStyleSheet("QLineEdit { \n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"")
        self.loguser_input.setText("")
        self.loguser_input.setObjectName("loguser_input")
        self.login_button = QtWidgets.QPushButton(self.login_page)
        self.login_button.setGeometry(QtCore.QRect(500, 530, 241, 51))
        self.login_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(67, 160, 233);\n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 170, 255);\n"
"}")
        self.login_button.setObjectName("login_button")
        self.forgot_password_cmd = QtWidgets.QCommandLinkButton(self.login_page)
        self.forgot_password_cmd.setGeometry(QtCore.QRect(440, 690, 222, 48))
        self.forgot_password_cmd.setObjectName("forgot_password_cmd")
        self.bg_login = QtWidgets.QLabel(self.login_page)
        self.bg_login.setGeometry(QtCore.QRect(0, 0, 1281, 761))
        self.bg_login.setObjectName("bg_login")
        self.logpass_input = QtWidgets.QLineEdit(self.login_page)
        self.logpass_input.setGeometry(QtCore.QRect(450, 400, 351, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.logpass_input.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.logpass_input.setFont(font)
        self.logpass_input.setStyleSheet("QLineEdit { \n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}")
        self.logpass_input.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.logpass_input.setText("")
        self.logpass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.logpass_input.setObjectName("logpass_input")
        self.logsign_button = QtWidgets.QPushButton(self.login_page)
        self.logsign_button.setGeometry(QtCore.QRect(440, 630, 161, 51))
        self.logsign_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(67, 160, 233);\n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 170, 255);\n"
"}")
        self.logsign_button.setObjectName("logsign_button")
        self.warn_label_log = QtWidgets.QLabel(self.login_page)
        self.warn_label_log.setGeometry(QtCore.QRect(450, 470, 351, 41))
        self.warn_label_log.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.warn_label_log.setText("")
        self.warn_label_log.setObjectName("warn_label_log")
        self.logquit_button = QtWidgets.QPushButton(self.login_page)
        self.logquit_button.setGeometry(QtCore.QRect(640, 630, 161, 51))
        self.logquit_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(67, 160, 233);\n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 170, 255);\n"
"}")
        self.logquit_button.setObjectName("logquit_button")
        self.bg_login.raise_()
        self.loguser_input.raise_()
        self.login_button.raise_()
        self.forgot_password_cmd.raise_()
        self.logpass_input.raise_()
        self.logsign_button.raise_()
        self.warn_label_log.raise_()
        self.logquit_button.raise_()
        self.entry.addWidget(self.login_page)
        self.signup_page = QtWidgets.QWidget()
        self.signup_page.setObjectName("signup_page")
        self.bg_pic = QtWidgets.QLabel(self.signup_page)
        self.bg_pic.setGeometry(QtCore.QRect(0, -80, 1241, 951))
        self.bg_pic.setMinimumSize(QtCore.QSize(1221, 821))
        self.bg_pic.setObjectName("bg_pic")
        self.signlogin_button = QtWidgets.QPushButton(self.signup_page)
        self.signlogin_button.setGeometry(QtCore.QRect(440, 650, 161, 51))
        self.signlogin_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(67, 160, 233);\n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 170, 255);\n"
"}")
        self.signlogin_button.setObjectName("signlogin_button")
        self.signup_button = QtWidgets.QPushButton(self.signup_page)
        self.signup_button.setGeometry(QtCore.QRect(490, 550, 261, 61))
        self.signup_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(67, 160, 233);\n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 170, 255);\n"
"}")
        self.signup_button.setObjectName("signup_button")
        self.signuser_input = QtWidgets.QLineEdit(self.signup_page)
        self.signuser_input.setGeometry(QtCore.QRect(460, 320, 341, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.signuser_input.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.signuser_input.setFont(font)
        self.signuser_input.setStyleSheet("QLineEdit { \n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QLineEditor:hover{\n"
"    border: 2px solid rgb(48,50,62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85,179,255);\n"
"}")
        self.signuser_input.setText("")
        self.signuser_input.setObjectName("signuser_input")
        self.signpass_input = QtWidgets.QLineEdit(self.signup_page)
        self.signpass_input.setGeometry(QtCore.QRect(460, 400, 341, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.signpass_input.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.signpass_input.setFont(font)
        self.signpass_input.setStyleSheet("QLineEdit { \n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QLineEditor:hover{\n"
"    border: 2px solid rgb(48,50,62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85,179,255);\n"
"}")
        self.signpass_input.setText("")
        self.signpass_input.setObjectName("signpass_input")
        self.signemail_input = QtWidgets.QLineEdit(self.signup_page)
        self.signemail_input.setGeometry(QtCore.QRect(460, 480, 341, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.signemail_input.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.signemail_input.setFont(font)
        self.signemail_input.setStyleSheet("QLineEdit { \n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QLineEditor:hover{\n"
"    border: 2px solid rgb(48,50,62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85,179,255);\n"
"}")
        self.signemail_input.setText("")
        self.signemail_input.setObjectName("signemail_input")
        self.sign_label = QtWidgets.QLabel(self.signup_page)
        self.sign_label.setGeometry(QtCore.QRect(500, 580, 241, 91))
        self.sign_label.setObjectName("sign_label")
        self.warn_label_sign = QtWidgets.QLabel(self.signup_page)
        self.warn_label_sign.setGeometry(QtCore.QRect(450, 710, 351, 41))
        self.warn_label_sign.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.warn_label_sign.setText("")
        self.warn_label_sign.setObjectName("warn_label_sign")
        self.logsign_button_2 = QtWidgets.QPushButton(self.signup_page)
        self.logsign_button_2.setGeometry(QtCore.QRect(640, 650, 161, 51))
        self.logsign_button_2.setStyleSheet("QPushButton{\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(67, 160, 233);\n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 170, 255);\n"
"}")
        self.logsign_button_2.setObjectName("logsign_button_2")
        self.entry.addWidget(self.signup_page)
        self.vertification = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.vertification.setFont(font)
        self.vertification.setObjectName("vertification")
        self.bg_vert = QtWidgets.QLabel(self.vertification)
        self.bg_vert.setGeometry(QtCore.QRect(0, 0, 1241, 761))
        self.bg_vert.setObjectName("bg_vert")
        #self.warn_label_vert = QtWidgets.QLabel(self.vertification)
        #self.warn_label_vert.setGeometry(QtCore.QRect(450, 640, 361, 51))
        #self.warn_label_vert.setText("")
        #self.warn_label_vert.setObjectName("warn_label_vert")
        self.send_cmd = QtWidgets.QCommandLinkButton(self.vertification)
        self.send_cmd.setGeometry(QtCore.QRect(450, 630, 341, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setWeight(50)
        self.send_cmd.setFont(font)
        self.send_cmd.setObjectName("send_cmd")
        self.vertify_button = QtWidgets.QPushButton(self.vertification)
        self.vertify_button.setGeometry(QtCore.QRect(500, 560, 241, 61))
        self.vertify_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(67, 160, 233);\n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 170, 255);\n"
"}")
        self.vertify_button.setObjectName("vertify_button")
        self.vertcode_input = QtWidgets.QLineEdit(self.vertification)
        self.vertcode_input.setGeometry(QtCore.QRect(450, 420, 351, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.vertcode_input.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Guttman Haim")
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.vertcode_input.setFont(font)
        self.vertcode_input.setStyleSheet("QLineEdit { \n"
"    \n"
"    font: 48pt \"Guttman Haim\";\n"
"    background-color: rgba(255,255,255);\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QLineEditor:hover{\n"
"    border: 2px solid rgb(48,50,62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85,179,255);\n"
"}")
        self.vertcode_input.setText("")
        self.vertcode_input.setMaxLength(4)
        self.vertcode_input.setPlaceholderText("")
        self.vertcode_input.setObjectName("vertcode_input")
        self.return_cmd = QtWidgets.QCommandLinkButton(self.vertification)
        self.return_cmd.setGeometry(QtCore.QRect(450, 680, 341, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setWeight(50)
        self.return_cmd.setFont(font)
        self.return_cmd.setObjectName("return_cmd")
        self.entry.addWidget(self.vertification)
        self.main_app = QtWidgets.QWidget()
        self.main_app.setObjectName("main_app")
        self.bg_app = QtWidgets.QLabel(self.main_app)
        self.bg_app.setGeometry(QtCore.QRect(0, -40, 1251, 821))
        self.bg_app.setPixmap(QtGui.QPixmap(":/pictures/5.png"))
        self.bg_app.setObjectName("bg_app")
        self.start_button = QtWidgets.QPushButton(self.main_app)
        self.start_button.setGeometry(QtCore.QRect(670, 620, 61, 91))
        self.start_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(67, 160, 233);\n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 170, 255);\n"
"}")
        self.start_button.setText("")
        self.start_button.setObjectName("start_button")
        self.send_button = QtWidgets.QPushButton(self.main_app)
        self.send_button.setGeometry(QtCore.QRect(500, 680, 121, 41))
        self.send_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(67, 160, 233);\n"
"    background-color: rgba(255,255,255,0);\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 170, 255);\n"
"}")
        self.send_button.setText("")
        self.send_button.setObjectName("send_button")
        self.textbox = QtWidgets.QLineEdit(self.main_app)
        self.textbox.setGeometry(QtCore.QRect(50, 610, 441, 111))
        self.textbox.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;")
        self.textbox.setObjectName("textbox")
        self.serch_user_line = QtWidgets.QLineEdit(self.main_app)
        self.serch_user_line.setGeometry(QtCore.QRect(970, 110, 171, 41))
        self.serch_user_line.setObjectName("serch_user_line")
        self.search_user_button = QtWidgets.QPushButton(self.main_app)
        self.search_user_button.setGeometry(QtCore.QRect(1150, 110, 41, 41))
        self.search_user_button.setObjectName("search_user_button")
        self.name_label = QtWidgets.QLabel(self.main_app)
        self.name_label.setGeometry(QtCore.QRect(40, 20, 301, 31))
        self.name_label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.entry.addWidget(self.main_app)
        MainWindow.setCentralWidget(self.stack)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1240, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_bg.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/4.png\"/></p></body></html>"))
        self.open_button.setText(_translate("MainWindow", " Continue "))
        self.loguser_input.setPlaceholderText(_translate("MainWindow", "   Username"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.forgot_password_cmd.setText(_translate("MainWindow", "Forgot my password"))
        self.bg_login.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/2.png\"/></p></body></html>"))
        self.logpass_input.setPlaceholderText(_translate("MainWindow", "   Password"))
        self.logsign_button.setText(_translate("MainWindow", "Sign Up"))
        self.logquit_button.setText(_translate("MainWindow", "Quit"))
        self.bg_pic.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/1.png\"/></p></body></html>"))
        self.signlogin_button.setText(_translate("MainWindow", "Login"))
        self.signup_button.setText(_translate("MainWindow", "Sign Up"))
        self.signuser_input.setPlaceholderText(_translate("MainWindow", "   Username"))
        self.signpass_input.setPlaceholderText(_translate("MainWindow", "   Password"))
        self.signemail_input.setPlaceholderText(_translate("MainWindow", "   Email"))
        self.sign_label.setText(_translate("MainWindow", "* Password must contain 8 characters"))
        self.logsign_button_2.setText(_translate("MainWindow", "Quit"))
        self.bg_vert.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/3.png\"/></p></body></html>"))
        self.send_cmd.setText(_translate("MainWindow", "send vertification code again..."))
        self.vertify_button.setText(_translate("MainWindow", "Verify"))
        self.return_cmd.setText(_translate("MainWindow", "return back to sign up"))
        self.bg_app.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/5.png\"/></p></body></html>"))
        self.search_user_button.setText(_translate("MainWindow", "Go"))
#import img_rc
